version: '3.3'
services:
  mysql_mariadb:
    container_name: mysql_mariadb
    image: 'mariadb:latest'
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    restart: always

    volumes:
      - .\data:/var/lib/mysql/

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
