version: "3"
services:
  tomcat:
    container_name: tomcat
    image: bitnami/tomcat:latest
    environment:
      - TOMCAT_USERNAME=root
      - TOMCAT_PASSWORD=root
    links:
      - db:mysql
    ports:
      - 8080:8080
    volumes:
      - .\data_tomcat:/bitnami/tomcat

  db:
    container_name: tomcat_mysql
    image: 'mysql:8'
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
    command: --default-authentication-plugin=mysql_native_password

    volumes:
    - .\data_mysql:/var/lib/mysql/

  phpmyadmin:
    container_name: tomcat_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - 8081:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql



